// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comm.proto

package protoComm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// 基本账户信息
type Source struct {
	// 店铺ID
	StoreId int64 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 用户ID
	Uid int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// 企业用户ID
	CustomerId int64 `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// 请求来源 0后台管理 1企业管理端 2用户管理端 3用户客户端
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// 平台来源
	Platform int32 `protobuf:"varint,5,opt,name=platform,proto3" json:"platform,omitempty"`
	// 当前时区（店铺时区）
	TimeZone             int64    `protobuf:"varint,6,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{1}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *Source) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Source) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Source) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Source) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *Source) GetTimeZone() int64 {
	if m != nil {
		return m.TimeZone
	}
	return 0
}

// 分页
type PageInfo struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderKey             string   `protobuf:"bytes,3,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{2}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageInfo) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageInfo) GetOrderKey() string {
	if m != nil {
		return m.OrderKey
	}
	return ""
}

type ResultPage struct {
	List                 []byte   `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultPage) Reset()         { *m = ResultPage{} }
func (m *ResultPage) String() string { return proto.CompactTextString(m) }
func (*ResultPage) ProtoMessage()    {}
func (*ResultPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{3}
}

func (m *ResultPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultPage.Unmarshal(m, b)
}
func (m *ResultPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultPage.Marshal(b, m, deterministic)
}
func (m *ResultPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultPage.Merge(m, src)
}
func (m *ResultPage) XXX_Size() int {
	return xxx_messageInfo_ResultPage.Size(m)
}
func (m *ResultPage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultPage.DiscardUnknown(m)
}

var xxx_messageInfo_ResultPage proto.InternalMessageInfo

func (m *ResultPage) GetList() []byte {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ResultPage) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// 默认提交
type Req struct {
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{4}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 默认输出
type Result struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 []byte            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Result) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Result) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 使用到的权益调用数据
type UseBenefit struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32             `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Aid                  int64             `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`
	Value                map[string]string `protobuf:"bytes,4,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UseBenefit) Reset()         { *m = UseBenefit{} }
func (m *UseBenefit) String() string { return proto.CompactTextString(m) }
func (*UseBenefit) ProtoMessage()    {}
func (*UseBenefit) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{6}
}

func (m *UseBenefit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseBenefit.Unmarshal(m, b)
}
func (m *UseBenefit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseBenefit.Marshal(b, m, deterministic)
}
func (m *UseBenefit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseBenefit.Merge(m, src)
}
func (m *UseBenefit) XXX_Size() int {
	return xxx_messageInfo_UseBenefit.Size(m)
}
func (m *UseBenefit) XXX_DiscardUnknown() {
	xxx_messageInfo_UseBenefit.DiscardUnknown(m)
}

var xxx_messageInfo_UseBenefit proto.InternalMessageInfo

func (m *UseBenefit) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UseBenefit) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UseBenefit) GetAid() int64 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *UseBenefit) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "protoComm.empty")
	proto.RegisterType((*Source)(nil), "protoComm.source")
	proto.RegisterType((*PageInfo)(nil), "protoComm.pageInfo")
	proto.RegisterType((*ResultPage)(nil), "protoComm.resultPage")
	proto.RegisterType((*Req)(nil), "protoComm.req")
	proto.RegisterType((*Result)(nil), "protoComm.result")
	proto.RegisterMapType((map[string]string)(nil), "protoComm.result.HeaderEntry")
	proto.RegisterType((*UseBenefit)(nil), "protoComm.UseBenefit")
	proto.RegisterMapType((map[string]string)(nil), "protoComm.UseBenefit.ValueEntry")
}

func init() { proto.RegisterFile("comm.proto", fileDescriptor_84d45c80f8c19d36) }

var fileDescriptor_84d45c80f8c19d36 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0xc9, 0x24, 0x93, 0xa9, 0x59, 0x64, 0x69, 0x3c, 0x64, 0x47, 0xc4, 0x21, 0x78, 0x98,
	0x53, 0x16, 0x14, 0x97, 0x55, 0x6f, 0x2b, 0x82, 0x83, 0x2c, 0x48, 0xfc, 0x40, 0xf6, 0x32, 0xb4,
	0x93, 0x1a, 0x0d, 0xa6, 0xd3, 0xb1, 0xbb, 0x23, 0x64, 0xfe, 0x8e, 0x7f, 0xc1, 0xa3, 0x3f, 0x4e,
	0xaa, 0x92, 0xc9, 0xcc, 0xc1, 0x8b, 0xa7, 0x7e, 0xf5, 0xaa, 0xfa, 0xf5, 0x7b, 0x54, 0x03, 0x6c,
	0xb5, 0x52, 0x59, 0x63, 0xb4, 0xd3, 0x62, 0xc6, 0xc7, 0x2b, 0xad, 0x54, 0x3a, 0x85, 0x10, 0x55,
	0xe3, 0xba, 0xf4, 0x97, 0x07, 0x91, 0xd5, 0xad, 0xd9, 0xa2, 0xb8, 0x80, 0xd8, 0x3a, 0x6d, 0x70,
	0x53, 0x16, 0x89, 0xb7, 0xf4, 0x56, 0x41, 0x3e, 0xe5, 0x7a, 0x5d, 0x88, 0x73, 0x08, 0xda, 0xb2,
	0x48, 0x7c, 0x66, 0x09, 0x8a, 0x47, 0x30, 0xdf, 0xb6, 0xd6, 0x69, 0x85, 0x86, 0xe6, 0x03, 0xee,
	0xc0, 0x81, 0x5a, 0x17, 0x42, 0xc0, 0xc4, 0x75, 0x0d, 0x26, 0x93, 0xa5, 0xb7, 0x0a, 0x73, 0xc6,
	0x62, 0x01, 0x71, 0x53, 0x49, 0xb7, 0xd3, 0x46, 0x25, 0x21, 0xf3, 0x63, 0x2d, 0x1e, 0xc0, 0xcc,
	0x95, 0x0a, 0x37, 0x7b, 0x5d, 0x63, 0x12, 0xb1, 0x5c, 0x4c, 0xc4, 0x9d, 0xae, 0x31, 0xfd, 0x0c,
	0x71, 0x23, 0xbf, 0xe2, 0xba, 0xde, 0x69, 0x12, 0x26, 0x3c, 0x58, 0x64, 0x4c, 0x97, 0xe9, 0xdc,
	0xd8, 0x72, 0x8f, 0x83, 0x4b, 0xbe, 0xf0, 0xbe, 0xdc, 0x73, 0x53, 0x9b, 0x02, 0xcd, 0xe6, 0x3b,
	0x76, 0x6c, 0x74, 0x96, 0xc7, 0x4c, 0xbc, 0xc5, 0x2e, 0xbd, 0x02, 0x30, 0x68, 0xdb, 0xca, 0xbd,
	0x23, 0x1d, 0x01, 0x93, 0xaa, 0xb4, 0x8e, 0xb5, 0xcf, 0x72, 0xc6, 0xe2, 0x3e, 0x84, 0x4e, 0x3b,
	0x59, 0x0d, 0xba, 0x7d, 0x91, 0x5e, 0x40, 0x60, 0xf0, 0x07, 0x5d, 0x28, 0xa4, 0x93, 0x9c, 0xf2,
	0x2c, 0x67, 0x9c, 0xfe, 0xf1, 0x20, 0xea, 0x35, 0xa9, 0xbd, 0xd5, 0x45, 0xef, 0x35, 0xcc, 0x19,
	0x8b, 0x04, 0xa6, 0x0a, 0xad, 0xa5, 0x08, 0x3e, 0x9b, 0x39, 0x94, 0xe2, 0x19, 0x44, 0xdf, 0x50,
	0x16, 0x68, 0x92, 0x60, 0x19, 0xac, 0xe6, 0x4f, 0x1e, 0x66, 0xe3, 0xc2, 0xb2, 0x5e, 0x30, 0x7b,
	0xc3, 0xfd, 0xd7, 0xb5, 0x33, 0x5d, 0x3e, 0x0c, 0xff, 0xcb, 0xc3, 0xe2, 0x39, 0xcc, 0x4f, 0x46,
	0x69, 0x7f, 0x14, 0xde, 0xe3, 0xf7, 0x08, 0x52, 0xaa, 0x9f, 0xb2, 0x6a, 0x0f, 0x1e, 0xfa, 0xe2,
	0x85, 0x7f, 0xed, 0xa5, 0xbf, 0x3d, 0x80, 0x8f, 0x16, 0x6f, 0xb0, 0xc6, 0x5d, 0xe9, 0xc4, 0x3d,
	0xf0, 0x87, 0xff, 0x10, 0xe6, 0x7e, 0x79, 0xdc, 0xab, 0x7f, 0xb2, 0xd7, 0x73, 0x08, 0xe4, 0xf8,
	0x09, 0x08, 0x8a, 0xab, 0x83, 0xfc, 0x84, 0x93, 0x2c, 0x4f, 0x92, 0x1c, 0xb5, 0xb3, 0x4f, 0x34,
	0xd2, 0x87, 0xe9, 0xc7, 0x17, 0xd7, 0x00, 0x47, 0xf2, 0x7f, 0x6c, 0xdf, 0x3c, 0xbe, 0x4b, 0x6f,
	0xbb, 0x0f, 0x68, 0xdd, 0xad, 0xac, 0xaa, 0x4b, 0x7e, 0x6e, 0xad, 0x9a, 0x4b, 0xfa, 0xfe, 0x2f,
	0xc7, 0xc7, 0xbf, 0x44, 0x0c, 0x9f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x35, 0xd5, 0x3c,
	0x17, 0x03, 0x00, 0x00,
}
